return {
  rifle = "ui/uiskin/rifle.svg"
  rifle_veteran = "ui/uiskin/rifle_veteran.svg"
  rifle_2 = "ui/uiskin/rifle.svg"
  rifle_2_veteran = "ui/uiskin/rifle_veteran.svg"
  rifle_3 = "ui/uiskin/rifle.svg"
  rifle_3_veteran = "ui/uiskin/rifle_veteran.svg"
  rifle_uk = "ui/uiskin/rifle.svg"
  rifle_uk_veteran = "ui/uiskin/rifle_veteran.svg"
  rifle_it = "ui/uiskin/rifle.svg"
  rifle_it_veteran = "ui/uiskin/rifle_veteran.svg"

  sniper = "ui/uiskin/sniper_rifle.svg"
  sniper_veteran = "ui/uiskin/sniper_rifle_veteran.svg"
  sniper_2 = "ui/uiskin/sniper_rifle.svg"
  sniper_2_veteran = "ui/uiskin/sniper_rifle_veteran.svg"
  sniper_3 = "ui/uiskin/sniper_rifle.svg"
  sniper_3_veteran = "ui/uiskin/sniper_rifle_veteran.svg"

  radioman = "ui/uiskin/radioman.svg"
  radioman_veteran = "ui/uiskin/radioman_veteran.svg"
  radioman_2 = "ui/uiskin/radioman.svg"
  radioman_2_veteran = "ui/uiskin/radioman_veteran.svg"

  mortarman = "ui/uiskin/mortarman.svg"
  mortarman_veteran = "ui/uiskin/mortarman_veteran.svg"
  mortarman_2 = "ui/uiskin/mortarman.svg"
  mortarman_2_veteran = "ui/uiskin/mortarman_veteran.svg"

  assault = "ui/uiskin/submachine_gun.svg"
  assault_veteran = "ui/uiskin/submachine_gun_veteran.svg"
  assault_2 = "ui/uiskin/submachine_gun.svg"
  assault_2_veteran = "ui/uiskin/submachine_gun_veteran.svg"
  assault_3 = "ui/uiskin/submachine_gun.svg"
  assault_3_veteran = "ui/uiskin/submachine_gun_veteran.svg"

  anti_tank = "ui/uiskin/launcher.svg"
  anti_tank_veteran = "ui/uiskin/launcher_veteran.svg"
  anti_tank_2 = "ui/uiskin/launcher.svg"
  anti_tank_2_veteran = "ui/uiskin/launcher_veteran.svg"

  mgun = "ui/uiskin/machine_gun.svg"
  mgun_veteran = "ui/uiskin/machine_gun_veteran.svg"
  mgun_2 = "ui/uiskin/machine_gun.svg"
  mgun_2_veteran = "ui/uiskin/machine_gun_veteran.svg"
  mgun_3 = "ui/uiskin/machine_gun.svg"
  mgun_3_veteran = "ui/uiskin/machine_gun_veteran.svg"

  engineer = "ui/uiskin/engineer.svg"
  engineer_veteran = "ui/uiskin/engineer_veteran.svg"
  engineer_2 = "ui/uiskin/engineer.svg"
  engineer_2_veteran = "ui/uiskin/engineer_veteran.svg"
  engineer_uk = "ui/uiskin/engineer.svg"
  engineer_uk_veteran = "ui/uiskin/engineer_veteran.svg"
  engineer_it = "ui/uiskin/engineer.svg"
  engineer_it_veteran = "ui/uiskin/engineer_veteran.svg"
  biker_engineer_premium_1 = "ui/uiskin/engineer.svg"
  biker_engineer_premium_1_veteran = "ui/uiskin/engineer_veteran.svg"
  mgun_2_engineer_premium_1 = "ui/uiskin/engineer.svg"
  mgun_2_engineer_premium_1_veteran = "ui/uiskin/engineer_veteran.svg"

  flametrooper = "ui/uiskin/flametrooper.svg"
  flametrooper_veteran = "ui/uiskin/flametrooper_veteran.svg"
  flametrooper_2 = "ui/uiskin/flametrooper.svg"
  flametrooper_2_veteran = "ui/uiskin/flametrooper_veteran.svg"

  pilot_fighter = "ui/uiskin/pilot_fighter.svg"
  pilot_fighter_veteran = "ui/uiskin/pilot_fighter_veteran.svg"
  pilot_fighter_2 = "ui/uiskin/pilot_fighter.svg"
  pilot_fighter_2_veteran = "ui/uiskin/pilot_fighter_veteran.svg"
  pilot_fighter_3 = "ui/uiskin/pilot_fighter.svg"
  pilot_fighter_3_veteran = "ui/uiskin/pilot_fighter_veteran.svg"

  pilot_assaulter = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"
  pilot_assaulter_2 = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_2_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"
  pilot_assaulter_3 = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_3_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"
  pilot_assaulter_uk = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_uk_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"
  pilot_assaulter_it = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_it_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"

  tanker = "ui/uiskin/driver_tank.svg"
  tanker_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_2 = "ui/uiskin/driver_tank.svg"
  tanker_2_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_3 = "ui/uiskin/driver_tank.svg"
  tanker_3_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_uk = "ui/uiskin/driver_tank.svg"
  tanker_uk_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_it = "ui/uiskin/driver_tank.svg"
  tanker_it_veteran = "ui/uiskin/driver_tank_veteran.svg"

  biker = "ui/uiskin/biker.svg"
  biker_veteran = "ui/uiskin/biker_veteran.svg"
  biker_premium_1 = "ui/uiskin/biker.svg"
  biker_premium_1_veteran = "ui/uiskin/biker_veteran.svg"

  medic = "ui/uiskin/medic.svg"
  medic_veteran = "ui/uiskin/medic_veteran.svg"
  medic_2_premium_1 = "ui/uiskin/medic.svg"
  medic_2_premium_1_veteran = "ui/uiskin/medic_veteran.svg"
  medic_2_premium_1_engineer = "ui/uiskin/engineer.svg"
  medic_2_premium_1_engineer_veteran = "ui/uiskin/engineer_veteran.svg"

  rifle_3_premium_1 = "ui/uiskin/rifle_premium.svg"
  rifle_3_premium_1_veteran = "ui/uiskin/rifle_premium_veteran.svg"
  rifle_3_premium_2 = "ui/uiskin/rifle_premium.svg"
  rifle_3_premium_2_veteran = "ui/uiskin/rifle_premium_veteran.svg"
  rifle_premium_1 = "ui/uiskin/rifle_premium.svg"
  rifle_premium_1_veteran = "ui/uiskin/rifle_premium_veteran.svg"
  assault_premium_1 = "ui/uiskin/submachine_gun_premium.svg"
  assault_premium_1_veteran = "ui/uiskin/submachine_gun_premium_veteran.svg"
  assault_premium_1_ch = "ui/uiskin/submachine_gun_premium.svg"
  assault_premium_1_veteran_ch = "ui/uiskin/submachine_gun_premium_veteran.svg"
  assault_premium_2 = "ui/uiskin/submachine_gun.svg"
  assault_premium_2_veteran = "ui/uiskin/submachine_gun_veteran.svg"
  assault_premium_3 = "ui/uiskin/submachine_gun_premium.svg"
  assault_premium_3_veteran = "ui/uiskin/submachine_gun_premium_veteran.svg"
  assault_event_1 = "ui/uiskin/submachine_gun_premium.svg"
  assault_event_1_veteran = "ui/uiskin/submachine_gun_premium_veteran.svg"
  assault_1_premium_1 = "ui/uiskin/submachine_gun_premium.svg"
  assault_1_premium_1_veteran = "ui/uiskin/submachine_gun_premium_veteran.svg"
  assault_2_premium_1 = "ui/uiskin/submachine_gun_premium.svg"
  assault_2_premium_1_veteran = "ui/uiskin/submachine_gun_premium_veteran.svg"
  assault_2_premium_2 = "ui/uiskin/submachine_gun_premium.svg"
  assault_2_premium_2_veteran = "ui/uiskin/submachine_gun_premium_veteran.svg"
  assault_2_premium_2_engineer = "ui/uiskin/engineer.svg"
  assault_2_premium_2_engineer_veteran = "ui/uiskin/engineer_veteran.svg"
  assault_3_premium_1 = "ui/uiskin/submachine_gun_premium.svg"
  assault_3_premium_1_veteran = "ui/uiskin/submachine_gun_premium_veteran.svg"
  assault_3_premium_1_engineer = "ui/uiskin/engineer.svg"
  assault_3_premium_1_engineer_veteran = "ui/uiskin/engineer_veteran.svg"
  mgun_premium_1 = "ui/uiskin/machine_gun_premium.svg"
  mgun_premium_1_veteran = "ui/uiskin/machine_gun_veteran.svg"
  mgun_premium_1_legacy = "ui/uiskin/machine_gun_premium.svg"
  mgun_premium_1_legacy_veteran = "ui/uiskin/machine_gun_veteran.svg"
  mgun_2_premium_1 = "ui/uiskin/machine_gun_premium.svg"
  mgun_2_premium_1_veteran = "ui/uiskin/machine_gun_veteran.svg"
  mgun_2_event_1 = "ui/uiskin/machine_gun_premium.svg"
  mgun_2_event_1_veteran = "ui/uiskin/machine_gun_veteran.svg"
  mgun_3_premium_1 = "ui/uiskin/machine_gun_premium.svg"
  mgun_3_premium_1_veteran = "ui/uiskin/machine_gun_veteran.svg"
  mgun_3_premium_1_engineer = "ui/uiskin/engineer.svg"
  mgun_3_premium_1_engineer_veteran = "ui/uiskin/engineer_veteran.svg"
  engineer_premium_1 = "ui/uiskin/engineer.svg"
  engineer_premium_1_veteran = "ui/uiskin/engineer_veteran.svg"
  engineer_premium_2 = "ui/uiskin/engineer.svg"
  engineer_premium_2_veteran = "ui/uiskin/engineer_veteran.svg"
  engineer_2_premium_1 = "ui/uiskin/engineer.svg"
  engineer_2_premium_1_veteran = "ui/uiskin/engineer_veteran.svg"
  pilot_fighter_premium_1 = "ui/uiskin/pilot_fighter.svg"
  pilot_fighter_premium_1_veteran = "ui/uiskin/pilot_fighter_veteran.svg"
  pilot_fighter_premium_2 = "ui/uiskin/pilot_fighter.svg"
  pilot_fighter_premium_2_veteran = "ui/uiskin/pilot_fighter_veteran.svg"
  tanker_premium_1 = "ui/uiskin/driver_tank.svg"
  tanker_premium_1_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_premium_2 = "ui/uiskin/driver_tank.svg"
  tanker_premium_2_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_premium_2_flametrooper = "ui/uiskin/driver_tank.svg"
  tanker_premium_2_flametrooper_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_2_premium_1 = "ui/uiskin/driver_tank.svg"
  tanker_2_premium_1_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_3_premium_1 = "ui/uiskin/driver_tank.svg"
  tanker_3_premium_1_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_3_premium_2 = "ui/uiskin/driver_tank.svg"
  tanker_3_premium_2_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_3_premium_3 = "ui/uiskin/driver_tank.svg"
  tanker_3_premium_3_veteran = "ui/uiskin/driver_tank_veteran.svg"
  tanker_3_premium_4 = "ui/uiskin/driver_tank.svg"
  tanker_3_premium_4_veteran = "ui/uiskin/driver_tank_veteran.svg"
  radioman_2_premium_1 = "ui/uiskin/radioman.svg"
  radioman_2_premium_1_veteran = "ui/uiskin/radioman_veteran.svg"
  radioman_2_premium_1_engineer = "ui/uiskin/engineer.svg"
  radioman_2_premium_1_engineer_veteran = "ui/uiskin/engineer_veteran.svg"
  sniper_2_premium_1 = "ui/uiskin/sniper_rifle.svg"
  sniper_2_premium_1_veteran = "ui/uiskin/sniper_rifle_veteran.svg"
  sniper_2_premium_1_engineer = "ui/uiskin/engineer.svg"
  sniper_2_premium_1_engineer_veteran = "ui/uiskin/engineer_veteran.svg"
  pilot_fighter_3_premium_1 = "ui/uiskin/pilot_fighter.svg"
  pilot_fighter_3_premium_1_veteran = "ui/uiskin/pilot_fighter_veteran.svg"
  pilot_fighter_3_premium_2 = "ui/uiskin/pilot_fighter.svg"
  pilot_fighter_3_premium_2_veteran = "ui/uiskin/pilot_fighter_veteran.svg"
  pilot_assaulter_2_premium_1 = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_2_premium_1_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"
  pilot_assaulter_2_premium_2 = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_2_premium_2_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"
  pilot_assaulter_premium_1 = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_premium_1_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"
  pilot_assaulter_3_premium_1 = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_3_premium_1_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"
  pilot_assaulter_3_premium_2 = "ui/uiskin/pilot_assaulter.svg"
  pilot_assaulter_3_premium_2_veteran = "ui/uiskin/pilot_assaulter_veteran.svg"





  launcher = "ui/uiskin/launcher.svg"
  launcher_veteran = "ui/uiskin/launcher_veteran.svg"

  soldier_tier1 = "ui/uiskin/research/soldier_tier1.svg"
  soldier_tier2 = "ui/uiskin/research/soldier_tier2.svg"
  soldier_tier3 = "ui/uiskin/research/soldier_tier3.svg"
  soldier_tier4 = "ui/uiskin/research/soldier_tier4.svg"
  soldier_tier5 = "ui/uiskin/research/soldier_tier5.svg"
  soldier_tier6 = "ui/uiskin/research/soldier_tier6.svg"
  squad_icon = "ui/uiskin/research/squad_icon.svg"
  squad_size = "ui/uiskin/research/squad_size.svg"
  reserve_upgrade_icon = "ui/uiskin/research/reserve_upgrade_icon.svg"
  squad_xp_boost_icon = "ui/uiskin/research/squad_xp_boost_icon.svg"
  building_unlock_1_icon = "ui/uiskin/building_aaa.svg"
  building_unlock_2_icon = "ui/uiskin/building_at.svg"
  building_unlock_3_icon = "ui/uiskin/building_mg_nest.svg"
  building_unlock_4_icon = "ui/uiskin/building_ampulomet.svg"
  inventory_upgrade_icon = "ui/uiskin/research/inventory_upgrade_icon.svg"
  class_xp_boost_icon = "ui/uiskin/research/class_xp_boost_icon.svg"
  side_slot_upgrade_icon = "ui/uiskin/pistol.svg"
  secondary_slot_upgrade_icon = "ui/uiskin/research/secondary_weap_slot_upgrade_icon.svg"
  backpack_slot_upgrade_icon = "ui/uiskin/research/inventory_upgrade_icon.svg"
  veteran_perk_icon = "ui/uiskin/research/veteran_perk_icon.svg"
  weapon_parts_boost_icon = "ui/uiskin/research/weapon_parts_boost_icon.svg"
  weapon_upgrade_cost_icon = "ui/uiskin/research/weapon_upgrade_cost_icon.svg"
  artillery_upgrade_icon = "ui/uiskin/radio.svg"
  artillery_type_unlock_1_icon = "ui/uiskin/grenade_smoke_icon.svg"
  artillery_type_unlock_2_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_3_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_4_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_5_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_6_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_7_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_8_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_9_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_10_icon = "ui/uiskin/marker_bomb.svg"
  artillery_type_unlock_11_icon = "ui/uiskin/marker_bomb.svg"

  squad_usa = "ui/uiskin/squad_usa_default.svg"
  squad_ussr ="ui/uiskin/squad_ussr_default.svg"
  squad_germany ="ui/uiskin/squad_germany_default.svg"

  // TODO cleanup unused icons
  shotgunner = "ui/uiskin/shotgun.svg"
  shotgunner_veteran = "ui/uiskin/shotgun_veteran.svg"
  german_squad_size = "ui/uiskin/research/german_squad_size.png"
  german_cross = "ui/uiskin/research/german_cross.png"
  star_soviet = "ui/uiskin/research/star_soviet.png"
  ussr_tank_helmet = "ui/uiskin/research/ussr_tank_helmet.png"
  soldier_05 = "ui/uiskin/research/soldier_05.png"
  soldier_07 = "ui/uiskin/research/soldier_07.png"
  ammo = "ui/uiskin/research/ammo.png"

}