// generated by dagor2/prog/scripts/genDasevents
enum ContextCommand {  // context_command_common::ContextCommand
  ECC_DISABLED = 0
  ECC_NONE = 1
  ECC_CANCEL = 2
  ECC_REVIVE = 3
  ECC_BRING_AMMO = 4
  ECC_DEFEND_POINT = 5
  ECC_ATTACK_TARGET = 6
  ECC_BUILD = 7
  ECC_PLANT_BOMB = 8
  ECC_DEFUSE_BOMB = 9
}

enum MedicHealState {  // medic_common::MedicHealState
  MHS_NONE = 0
  MHS_NEED_HEAL = 1
  MHS_NEED_REVIVE = 2
}

enum SquadBehaviour {  // squad_behaviour_command_common::SquadBehaviour
  ESB_AGRESSIVE = 0
  ESB_PASSIVE = 1
}

enum CanTerraformCheckResult {  // terraform_common::CanTerraformCheckResult
  Successful = 0
  OutOfHeightMap = 1
  DisallowedMaterials = 2
  NearByObjects = 3
}

return {
  ContextCommand
  MedicHealState
  SquadBehaviour
  CanTerraformCheckResult
}